// Package crypto seals the passwords stored in ~/.dodb/profiles.json.
//
// This is a byte-exact port of src-tauri/src/crypto.rs. Every constant, salt,
// iteration count and wire format below is load-bearing: an existing install's
// profiles.json holds ciphertext produced by the Rust build, and changing any
// of them means users silently lose every saved password. The golden vectors in
// testdata/golden/crypto_*.json were generated by the Rust code itself and are
// the guard against exactly that.
//
// Three key generations decrypt, one encrypts:
//
//	enc:v2:<iv>:<tag>:<body>   HKDF-SHA256 over the master secret  (current)
//	enc:<iv>:<tag>:<body>      PBKDF2 over the master secret       (v1)
//	enc:<iv>:<tag>:<body>      PBKDF2 over a hardcoded string      (legacy)
//
// v1 and legacy share a wire format, so an unversioned blob is tried against v1
// first and legacy second, mirroring decrypt_password.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hkdf"
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"sync"
)

// Derivation parameters. Do not touch: see the package comment.
var (
	saltV2    = []byte("dodb-per-device-salt-v2")
	saltLegal = []byte("dodb-salt-salt-v1")
	hkdfSalt  = []byte("dodb-hkdf-salt-v3")
)

const (
	hkdfInfo     = "dodb-profile-password-v2"
	legacySecret = "dodb-mac-secure-master-key-v1"
	iterations   = 100_000
	keyLength    = 32
	tagLength    = 16
	ivLength     = 12
)

// KeyUnavailableMarker mirrors crypto.rs's KEY_UNAVAILABLE_MARKER: the sentinel
// the profile layer substitutes when the master key cannot be resolved at all.
const KeyUnavailableMarker = "KEY_UNAVAILABLE"

// ErrUndecryptable is the Ok(None) arm of the Rust decrypt_password: the blob
// looks like dodb ciphertext but no known key generation opens it. Callers are
// expected to drop the password and keep the rest of the profile, not to fail.
var ErrUndecryptable = errors.New("crypto: ciphertext could not be opened with any known key")

// KeyUnavailableError reports that no master key could be resolved. It is
// deliberately distinct from ErrUndecryptable: one means "this blob is lost",
// the other means "ask again once the keychain is unlocked".
type KeyUnavailableError struct{ Reason string }

func (e *KeyUnavailableError) Error() string { return "crypto: master key unavailable: " + e.Reason }

func unavailable(format string, args ...any) error {
	return &KeyUnavailableError{Reason: fmt.Sprintf(format, args...)}
}

// Key generations are derived once and cached, but only on success, so a run
// that started with a locked keychain recovers when it is unlocked.
var (
	keyMu     sync.Mutex
	cachedV2  []byte
	cachedV1  []byte
	cachedLeg []byte
)

func pbkdf2Key(secret string, salt []byte) []byte {
	k, err := pbkdf2.Key(sha256.New, secret, salt, iterations, keyLength)
	if err != nil {
		// PBKDF2 only fails on a non-positive key length, which is a constant here.
		panic("crypto: pbkdf2: " + err.Error())
	}
	return k
}

// v2Key is HKDF-SHA256 over input keying material whose shape depends on where
// the secret came from — see secret() for why env and store differ.
func v2Key() ([]byte, error) {
	keyMu.Lock()
	defer keyMu.Unlock()
	if cachedV2 != nil {
		return cachedV2, nil
	}
	ms, err := secret()
	if err != nil {
		return nil, err
	}

	var ikm []byte
	switch ms.source {
	case sourceEnv:
		// A user-supplied secret may be a low-entropy passphrase, so it is
		// stretched before it becomes keying material.
		ikm = pbkdf2Key(ms.value, saltV2)
	default:
		// A stored secret is already 256 bits of hex. Note this is the ASCII of
		// the hex string, NOT the decoded bytes — matching secret.value.as_bytes().
		ikm = []byte(ms.value)
	}

	k, err := hkdf.Key(sha256.New, ikm, hkdfSalt, hkdfInfo, keyLength)
	if err != nil {
		return nil, fmt.Errorf("crypto: HKDF expand failed: %w", err)
	}
	cachedV2 = k
	return k, nil
}

func v1Key() ([]byte, error) {
	keyMu.Lock()
	defer keyMu.Unlock()
	if cachedV1 != nil {
		return cachedV1, nil
	}
	ms, err := secret()
	if err != nil {
		return nil, err
	}
	cachedV1 = pbkdf2Key(ms.value, saltV2)
	return cachedV1, nil
}

// legacyKey derives from a hardcoded string, so it needs no master secret and
// never fails. Blobs this old predate per-device keys entirely.
func legacyKey() []byte {
	keyMu.Lock()
	defer keyMu.Unlock()
	if cachedLeg == nil {
		cachedLeg = pbkdf2Key(legacySecret, saltLegal)
	}
	return cachedLeg
}

// Init resolves the master key up front so startup can report a problem before
// the user tries to open a connection. Mirrors crypto::init.
func Init() error {
	_, err := v2Key()
	return err
}

// EncryptPassword seals plain as enc:v2:<iv>:<tag>:<body>.
//
// Empty input and input that is already ciphertext pass through untouched, so
// re-saving a profile does not double-encrypt it.
func EncryptPassword(plain string) (string, error) {
	if plain == "" || strings.HasPrefix(plain, "enc:") {
		return plain, nil
	}
	key, err := v2Key()
	if err != nil {
		return "", err
	}
	aead, err := newGCM(key)
	if err != nil {
		return "", err
	}

	iv := make([]byte, ivLength)
	if _, err := rand.Read(iv); err != nil {
		return "", fmt.Errorf("crypto: could not read a nonce: %w", err)
	}

	sealed := aead.Seal(nil, iv, []byte(plain), nil)
	if len(sealed) < tagLength {
		return "", errors.New("crypto: AES-GCM output is missing its auth tag")
	}
	// Go appends the tag to the ciphertext; the dodb wire format carries it as
	// its own hex field. Split it back out.
	body, tag := sealed[:len(sealed)-tagLength], sealed[len(sealed)-tagLength:]

	return fmt.Sprintf("enc:v2:%s:%s:%s", hex.EncodeToString(iv), hex.EncodeToString(tag), hex.EncodeToString(body)), nil
}

// DecryptPassword opens a blob written by any key generation.
//
// Input that is empty or does not start with "enc:" is returned as-is: profiles
// written before encryption existed hold bare plaintext. A blob that cannot be
// opened returns ErrUndecryptable, which callers treat as "drop the password",
// not as a failure.
func DecryptPassword(blob string) (string, error) {
	if blob == "" || !strings.HasPrefix(blob, "enc:") {
		return blob, nil
	}

	parts := strings.Split(blob, ":")
	switch {
	case len(parts) == 5 && parts[1] == "v2":
		key, err := v2Key()
		if err != nil {
			return "", err
		}
		if plain, ok := open(parts[2], parts[3], parts[4], key); ok {
			return plain, nil
		}
		return "", ErrUndecryptable

	case len(parts) == 4:
		// v1 and legacy share this wire format, so try v1 and fall back.
		// A key-resolution failure propagates rather than silently degrading to
		// legacy, matching the `v1_key()?` in decrypt_password: legacy would
		// "succeed" at opening nothing and the real problem would go unreported.
		key, err := v1Key()
		if err != nil {
			return "", err
		}
		if plain, ok := open(parts[1], parts[2], parts[3], key); ok {
			return plain, nil
		}
		if plain, ok := open(parts[1], parts[2], parts[3], legacyKey()); ok {
			return plain, nil
		}
		return "", ErrUndecryptable

	default:
		return "", ErrUndecryptable
	}
}

func newGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("crypto: invalid AES key: %w", err)
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("crypto: could not construct AES-GCM: %w", err)
	}
	return aead, nil
}

// open reverses EncryptPassword's split: the tag is re-appended to the body
// before handing the blob to Go's AEAD, which expects them contiguous.
//
// Every failure is a plain "no" rather than an error, because callers only ever
// want to know whether the next key generation should be tried.
func open(ivHex, tagHex, bodyHex string, key []byte) (string, bool) {
	iv, err := hex.DecodeString(ivHex)
	if err != nil || len(iv) != ivLength {
		return "", false
	}
	tag, err := hex.DecodeString(tagHex)
	if err != nil || len(tag) != tagLength {
		return "", false
	}
	body, err := hex.DecodeString(bodyHex)
	if err != nil {
		return "", false
	}

	aead, err := newGCM(key)
	if err != nil {
		return "", false
	}
	joined := make([]byte, 0, len(body)+len(tag))
	joined = append(joined, body...)
	joined = append(joined, tag...)

	plain, err := aead.Open(nil, iv, joined, nil)
	if err != nil {
		return "", false
	}
	return string(plain), true
}

// resetForTest drops the derived-key cache. Tests drive several master secrets
// through one process, which the production sync.Once-style cache would pin.
func resetForTest() {
	keyMu.Lock()
	defer keyMu.Unlock()
	cachedV2, cachedV1, cachedLeg = nil, nil, nil
	resetSecretForTest()
}
