/**
 * Regenerates the self-hosted webfonts in public/fonts and src/styles/fonts.css.
 *
 * The app must run fully offline (native desktop build), so fonts are never
 * loaded from fonts.googleapis.com at runtime. Run this only when the font
 * families / weights below change:
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile, readdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const GOOGLE_CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=Bai+Jamjuree:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400" +
  "&family=JetBrains+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400" +
  "&display=swap";

// A modern UA is required, otherwise Google serves ttf instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = path.join(root, "public", "fonts");
const cssOut = path.join(root, "src", "styles", "fonts.css");

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function download(url, dest, attempts = 4) {
  for (let i = 1; i <= attempts; i++) {
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      if (buf.subarray(0, 4).toString("latin1") !== "wOF2") throw new Error("not a woff2 file");
      await writeFile(dest, buf);
      return buf.length;
    } catch (err) {
      if (i === attempts) throw new Error(`${path.basename(dest)}: ${err.message}`);
    }
  }
}

const res = await fetch(GOOGLE_CSS_URL, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`fetching font CSS failed: HTTP ${res.status}`);
const css = await res.text();

// Each face in Google's CSS is preceded by a /* subset */ comment.
const faces = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]*\})/g)].map(
  ([, subset, block]) => ({ subset, block })
);
if (!faces.length) throw new Error("no @font-face blocks found in font CSS");

await mkdir(fontsDir, { recursive: true });
for (const stale of await readdir(fontsDir)) {
  if (stale.endsWith(".woff2")) await rm(path.join(fontsDir, stale));
}

const blocks = [];
let bytes = 0;
for (const { subset, block } of faces) {
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const style = /font-style: (\w+)/.exec(block)[1];
  const weight = /font-weight: (\d+)/.exec(block)[1];
  const url = /url\((https:[^)]+)\)/.exec(block)[1];
  const file = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
  bytes += await download(url, path.join(fontsDir, file));
  blocks.push(block.replace(/url\(https:[^)]+\)/, `url('/fonts/${file}')`));
}

const header = `/* Self-hosted webfonts — the app makes no network requests for fonts.
   Generated by scripts/fetch-fonts.mjs; files live in public/fonts.
   Do not edit by hand — re-run \`node scripts/fetch-fonts.mjs\` instead. */\n\n`;
await writeFile(cssOut, header + blocks.join("\n") + "\n");

console.log(`${blocks.length} faces, ${(bytes / 1024).toFixed(0)} KB -> public/fonts + src/styles/fonts.css`);
