package api

import (
	"reflect"
	"testing"
)

func TestDialectHints(t *testing.T) {
	cases := []struct {
		name string
		text string
		want []string
	}{
		{
			name: "dodb header wins over the heuristics",
			text: "-- DODB Database Backup / Dump\n-- DODB-Dialect: postgres\n-- Flavour: PostgreSQL\nCREATE TABLE \"t\" (\"id\" integer GENERATED BY DEFAULT AS IDENTITY);\n",
			want: []string{"postgres"},
		},
		{
			name: "dodb header is not fooled by mysql-looking DDL",
			// AUTO_INCREMENT alone would fingerprint this as MySQL.
			text: "-- DODB-Dialect: mariadb\nCREATE TABLE `t` (`id` integer NOT NULL AUTO_INCREMENT) ENGINE=InnoDB;\n",
			want: []string{"mariadb"},
		},
		{
			name: "dodb header, sqlite",
			text: "-- DODB-Dialect: sqlite\nPRAGMA foreign_keys = OFF;\n",
			want: []string{"sqlite"},
		},
		{
			name: "mysqldump output",
			text: "/*!40101 SET NAMES utf8 */;\nCREATE TABLE `t` (`id` int) ENGINE=InnoDB;\n",
			want: []string{"mysql"},
		},
		{
			name: "pg_dump output",
			text: "SET search_path = public;\nCOPY public.t (id) FROM stdin;\n",
			want: []string{"postgres"},
		},
		{
			name: "nothing recognisable",
			text: "SELECT 1;\n",
			want: []string{},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := dialectHints(tc.text)
			if !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("dialectHints() = %v, want %v", got, tc.want)
			}
		})
	}
}
