import { DBType } from "../types";
import { isGeometryColumn } from "./gisUtils";

/**
 * Dialect-aware DDL generation for Postgres, MariaDB/MySQL and SQLite.
 *
 * Pure module: no React, no Tauri. Everything the table designer needs to turn
 * a draft into SQL lives here, so the preview can be regenerated on every
 * keystroke without a round-trip to the backend.
 */

export type OnAction = "NO ACTION" | "RESTRICT" | "CASCADE" | "SET NULL" | "SET DEFAULT";

export const ON_ACTIONS: OnAction[] = ["NO ACTION", "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT"];

export interface ColumnDraft {
  /** Stable client-side key for React lists. Not part of the SQL. */
  id: string;
  name: string;
  type: string;
  nullable: boolean;
  primaryKey: boolean;
  autoIncrement: boolean;
  defaultValue: string | null;
  /** Set only for columns that already exist in the database. */
  originalName?: string;
}

export interface IndexDraft {
  id: string;
  name: string;
  columns: string[];
  unique: boolean;
  originalName?: string;
}

export interface ForeignKeyDraft {
  id: string;
  name: string;
  columns: string[];
  refTable: string;
  refColumns: string[];
  onDelete: OnAction;
  onUpdate: OnAction;
  originalName?: string;
}

export interface TableDraft {
  name: string;
  originalName?: string;
  columns: ColumnDraft[];
  indexes: IndexDraft[];
  foreignKeys: ForeignKeyDraft[];
  /** Real PK constraint name, needed for Postgres DROP CONSTRAINT. */
  primaryKeyName?: string;
}

// ---------------------------------------------------------------------------
// Identifier quoting
// ---------------------------------------------------------------------------

const quoteCharFor = (d: DBType): string => (d === "mariadb" ? "`" : '"');

/** Quote a single identifier, doubling any embedded quote char. */
export function quoteIdent(name: string, d: DBType): string {
  const q = quoteCharFor(d);
  return q + name.split(q).join(q + q) + q;
}

/** Schema part of a possibly-qualified Postgres table name, else null. */
export function schemaOf(table: string): string | null {
  const i = table.indexOf(".");
  return i > 0 ? table.slice(0, i) : null;
}

/** Table name without its schema prefix. */
export function bareTableName(table: string): string {
  const i = table.indexOf(".");
  return i > 0 ? table.slice(i + 1) : table;
}

/**
 * Quote a table reference. Postgres tables may arrive schema-qualified
 * ("reporting.events") from get_tables, and each part must be quoted separately.
 */
export function quoteTableIdent(table: string, d: DBType): string {
  const schema = d === "postgres" ? schemaOf(table) : null;
  if (schema) {
    return quoteIdent(schema, d) + "." + quoteIdent(bareTableName(table), d);
  }
  return quoteIdent(table, d);
}

// ---------------------------------------------------------------------------
// Value / type rendering
// ---------------------------------------------------------------------------

const KEYWORD_DEFAULTS = [
  "NULL",
  "TRUE",
  "FALSE",
  "CURRENT_TIMESTAMP",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_USER",
  "LOCALTIMESTAMP",
];

/**
 * Render a user-entered DEFAULT. Numbers, keywords, function calls, casts and
 * already-quoted text pass through untouched; anything else is treated as a
 * string literal.
 */
export function renderDefault(raw: string): string {
  const t = raw.trim();
  if (!t) return "";
  const upper = t.toUpperCase();

  if (/^'[\s\S]*'$/.test(t)) return t;
  if (/^-?\d+(\.\d+)?$/.test(t)) return t;
  if (KEYWORD_DEFAULTS.includes(upper)) return t;
  if (/^[A-Za-z_][A-Za-z0-9_]*\s*\([\s\S]*\)$/.test(t)) return t;
  if (t.includes("::")) return t;

  return "'" + t.split("'").join("''") + "'";
}

const normType = (t: string): string => t.trim().toLowerCase().replace(/\s+/g, " ");

// ---------------------------------------------------------------------------
// Column definitions
// ---------------------------------------------------------------------------

/**
 * A single column definition as it appears inside CREATE TABLE, ADD COLUMN or
 * MariaDB's MODIFY COLUMN.
 */
function columnDef(col: ColumnDraft, d: DBType, sqliteInlinePk = false): string {
  // SQLite only auto-increments through this exact spelling.
  if (sqliteInlinePk) {
    return quoteIdent(col.name, d) + " INTEGER PRIMARY KEY AUTOINCREMENT";
  }

  const bits: string[] = [quoteIdent(col.name, d), col.type.trim()];

  if (col.autoIncrement) {
    // An auto-increment column takes no DEFAULT.
    if (d === "postgres") {
      bits.push("GENERATED BY DEFAULT AS IDENTITY");
    } else if (d === "mariadb") {
      bits.push("NOT NULL", "AUTO_INCREMENT");
    }
    return bits.join(" ");
  }

  if (!col.nullable) bits.push("NOT NULL");

  const def = col.defaultValue ? renderDefault(col.defaultValue) : "";
  if (def) bits.push("DEFAULT " + def);

  return bits.join(" ");
}

function fkClause(fk: ForeignKeyDraft, d: DBType): string {
  const named = fk.name.trim() ? "CONSTRAINT " + quoteIdent(fk.name.trim(), d) + " " : "";
  const cols = fk.columns.map((c) => quoteIdent(c, d)).join(", ");
  const refCols = fk.refColumns.map((c) => quoteIdent(c, d)).join(", ");

  let out = named + "FOREIGN KEY (" + cols + ") REFERENCES " + quoteTableIdent(fk.refTable, d) + " (" + refCols + ")";
  if (fk.onDelete && fk.onDelete !== "NO ACTION") out += " ON DELETE " + fk.onDelete;
  if (fk.onUpdate && fk.onUpdate !== "NO ACTION") out += " ON UPDATE " + fk.onUpdate;
  return out;
}

function createIndexStmt(idx: IndexDraft, table: string, d: DBType): string {
  const unique = idx.unique ? "UNIQUE " : "";
  const cols = idx.columns.map((c) => quoteIdent(c, d)).join(", ");
  return (
    "CREATE " + unique + "INDEX " + quoteIdent(idx.name.trim(), d) +
    " ON " + quoteTableIdent(table, d) + " (" + cols + ");"
  );
}

function dropIndexStmt(name: string, table: string, d: DBType): string {
  if (d === "mariadb") {
    return "DROP INDEX " + quoteIdent(name, d) + " ON " + quoteTableIdent(table, d) + ";";
  }
  // Postgres/SQLite drop indexes by name, not by table. In Postgres the index
  // lives in the same schema as its table.
  const schema = d === "postgres" ? schemaOf(table) : null;
  const target = schema ? quoteIdent(schema, d) + "." + quoteIdent(name, d) : quoteIdent(name, d);
  return "DROP INDEX " + target + ";";
}

const isIndexUsable = (i: IndexDraft): boolean => !!i.name.trim() && i.columns.length > 0;

const isFkUsable = (f: ForeignKeyDraft): boolean =>
  f.columns.length > 0 && !!f.refTable.trim() && f.refColumns.length === f.columns.length;

// ---------------------------------------------------------------------------
// CREATE TABLE
// ---------------------------------------------------------------------------

export function buildCreateTable(draft: TableDraft, d: DBType): string[] {
  const stmts: string[] = [];

  // In Postgres, geometry/geography types require the PostGIS extension
  if (d === "postgres" && draft.columns.some((c) => isGeometryColumn(c.type, c.name))) {
    stmts.push("CREATE EXTENSION IF NOT EXISTS postgis;");
  }

  const pkCols = draft.columns.filter((c) => c.primaryKey);

  // SQLite: a single auto-increment PK must be declared inline and must not
  // also get a table-level PRIMARY KEY clause.
  const sqliteInline = d === "sqlite" && pkCols.length === 1 && pkCols[0].autoIncrement;

  const lines = draft.columns.map(
    (c) => "  " + columnDef(c, d, sqliteInline && c.primaryKey && c.autoIncrement)
  );

  if (pkCols.length > 0 && !sqliteInline) {
    lines.push("  PRIMARY KEY (" + pkCols.map((c) => quoteIdent(c.name, d)).join(", ") + ")");
  }

  // Inline the FKs: SQLite cannot add them later, and it is valid everywhere.
  for (const fk of draft.foreignKeys) {
    if (isFkUsable(fk)) lines.push("  " + fkClause(fk, d));
  }

  const suffix = d === "mariadb" ? " ENGINE=InnoDB" : "";
  stmts.push(
    "CREATE TABLE " + quoteTableIdent(draft.name, d) + " (\n" + lines.join(",\n") + "\n)" + suffix + ";"
  );

  for (const idx of draft.indexes) {
    if (isIndexUsable(idx)) stmts.push(createIndexStmt(idx, draft.name, d));
  }

  return stmts;
}

// ---------------------------------------------------------------------------
// ALTER TABLE (diff)
// ---------------------------------------------------------------------------

const indexChanged = (a: IndexDraft, b: IndexDraft): boolean =>
  a.name !== b.name || a.unique !== b.unique || a.columns.join(",") !== b.columns.join(",");

const fkChanged = (a: ForeignKeyDraft, b: ForeignKeyDraft): boolean =>
  a.name !== b.name ||
  a.columns.join(",") !== b.columns.join(",") ||
  a.refTable !== b.refTable ||
  a.refColumns.join(",") !== b.refColumns.join(",") ||
  a.onDelete !== b.onDelete ||
  a.onUpdate !== b.onUpdate;

/**
 * Statements for one changed column.
 *
 * This is the sharpest dialect split in the module: MariaDB redefines the whole
 * column in a single MODIFY COLUMN, while Postgres needs one ALTER COLUMN per
 * facet that changed.
 */
function modifyColumnStmts(before: ColumnDraft, after: ColumnDraft, table: string, d: DBType): string[] {
  const typeChanged = normType(before.type) !== normType(after.type);
  const nullChanged = before.nullable !== after.nullable;
  const defChanged = (before.defaultValue ?? "") !== (after.defaultValue ?? "");
  const autoChanged = before.autoIncrement !== after.autoIncrement;

  if (!typeChanged && !nullChanged && !defChanged && !autoChanged) return [];

  const T = quoteTableIdent(table, d);

  if (d === "mariadb") {
    return ["ALTER TABLE " + T + " MODIFY COLUMN " + columnDef(after, d) + ";"];
  }

  const col = quoteIdent(after.name, d);
  const out: string[] = [];
  const type = after.type.trim();

  if (typeChanged) {
    out.push("ALTER TABLE " + T + " ALTER COLUMN " + col + " TYPE " + type + " USING " + col + "::" + type + ";");
  }
  if (nullChanged) {
    out.push("ALTER TABLE " + T + " ALTER COLUMN " + col + (after.nullable ? " DROP NOT NULL;" : " SET NOT NULL;"));
  }
  if (defChanged) {
    const def = after.defaultValue ? renderDefault(after.defaultValue) : "";
    out.push(
      def
        ? "ALTER TABLE " + T + " ALTER COLUMN " + col + " SET DEFAULT " + def + ";"
        : "ALTER TABLE " + T + " ALTER COLUMN " + col + " DROP DEFAULT;"
    );
  }
  if (autoChanged) {
    out.push(
      after.autoIncrement
        ? "ALTER TABLE " + T + " ALTER COLUMN " + col + " ADD GENERATED BY DEFAULT AS IDENTITY;"
        : "ALTER TABLE " + T + " ALTER COLUMN " + col + " DROP IDENTITY IF EXISTS;"
    );
  }
  return out;
}

/**
 * Generate the ALTER statements that turn `original` into `draft`.
 *
 * Ordering is deliberate, not incidental: constraints come off before the
 * columns they reference are touched, and the table rename goes last so every
 * preceding statement can address the table by its original name.
 */
export function diffTable(original: TableDraft, draft: TableDraft, d: DBType): string[] {
  const table = original.name;
  const T = quoteTableIdent(table, d);
  const out: string[] = [];

  // In Postgres, if any draft column has a geometry type, ensure postgis extension is loaded
  if (d === "postgres" && draft.columns.some((c) => isGeometryColumn(c.type, c.name))) {
    out.push("CREATE EXTENSION IF NOT EXISTS postgis;");
  }

  const origColsByName = new Map(original.columns.map((c) => [c.name, c]));
  const keptOriginalNames = new Set(
    draft.columns.map((c) => c.originalName).filter((n): n is string => !!n)
  );

  // 1. Drop foreign keys that were removed or edited (edited ones are re-added below).
  const dropFkWord = d === "mariadb" ? "FOREIGN KEY" : "CONSTRAINT";
  for (const fk of original.foreignKeys) {
    const kept = draft.foreignKeys.find((f) => f.originalName === fk.name);
    if (!kept || fkChanged(fk, kept)) {
      out.push("ALTER TABLE " + T + " DROP " + dropFkWord + " " + quoteIdent(fk.name, d) + ";");
    }
  }

  // 2. Drop indexes that were removed or edited.
  for (const ix of original.indexes) {
    const kept = draft.indexes.find((i) => i.originalName === ix.name);
    if (!kept || indexChanged(ix, kept)) out.push(dropIndexStmt(ix.name, table, d));
  }

  // 3. Rename columns before anything else refers to them by their new name.
  for (const c of draft.columns) {
    if (c.originalName && c.originalName !== c.name) {
      out.push(
        "ALTER TABLE " + T + " RENAME COLUMN " + quoteIdent(c.originalName, d) + " TO " + quoteIdent(c.name, d) + ";"
      );
    }
  }

  // 4. Drop removed columns.
  for (const c of original.columns) {
    if (!keptOriginalNames.has(c.name)) {
      out.push("ALTER TABLE " + T + " DROP COLUMN " + quoteIdent(c.name, d) + ";");
    }
  }

  // 5. Add new columns.
  for (const c of draft.columns) {
    if (!c.originalName) {
      out.push("ALTER TABLE " + T + " ADD COLUMN " + columnDef(c, d) + ";");
    }
  }

  // 6. Modify surviving columns.
  for (const c of draft.columns) {
    if (!c.originalName) continue;
    const before = origColsByName.get(c.originalName);
    if (before) out.push(...modifyColumnStmts(before, c, table, d));
  }

  // 7. Primary key.
  const beforePk = original.columns.filter((c) => c.primaryKey).map((c) => c.name).join(",");
  const afterPk = draft.columns.filter((c) => c.primaryKey).map((c) => c.name);
  if (beforePk !== afterPk.join(",")) {
    if (beforePk) {
      if (d === "mariadb") {
        out.push("ALTER TABLE " + T + " DROP PRIMARY KEY;");
      } else {
        const pkName = original.primaryKeyName || bareTableName(table) + "_pkey";
        out.push("ALTER TABLE " + T + " DROP CONSTRAINT " + quoteIdent(pkName, d) + ";");
      }
    }
    if (afterPk.length > 0) {
      out.push("ALTER TABLE " + T + " ADD PRIMARY KEY (" + afterPk.map((n) => quoteIdent(n, d)).join(", ") + ");");
    }
  }

  // 8. Create new and edited indexes.
  for (const ix of draft.indexes) {
    if (!isIndexUsable(ix)) continue;
    const before = ix.originalName ? original.indexes.find((i) => i.name === ix.originalName) : undefined;
    if (!before || indexChanged(before, ix)) out.push(createIndexStmt(ix, table, d));
  }

  // 9. Add new and edited foreign keys.
  for (const fk of draft.foreignKeys) {
    if (!isFkUsable(fk)) continue;
    const before = fk.originalName ? original.foreignKeys.find((f) => f.name === fk.originalName) : undefined;
    if (!before || fkChanged(before, fk)) {
      out.push("ALTER TABLE " + T + " ADD " + fkClause(fk, d) + ";");
    }
  }

  // 10. Rename the table last.
  if (draft.name.trim() && draft.name !== table) {
    out.push("ALTER TABLE " + T + " RENAME TO " + quoteIdent(bareTableName(draft.name.trim()), d) + ";");
  }

  return out;
}

// ---------------------------------------------------------------------------
// Destructive one-liners
// ---------------------------------------------------------------------------

export function buildDropTable(table: string, d: DBType): string {
  return "DROP TABLE " + quoteTableIdent(table, d) + ";";
}

export function buildTruncateTable(table: string, d: DBType): string {
  // SQLite has no TRUNCATE.
  if (d === "sqlite") return "DELETE FROM " + quoteTableIdent(table, d) + ";";
  return "TRUNCATE TABLE " + quoteTableIdent(table, d) + ";";
}

/** Best-effort CREATE TABLE for the read-only DDL tab. */
export function buildDdlPreview(draft: TableDraft, d: DBType): string {
  if (draft.columns.length === 0) {
    return "-- No columns found for table " + draft.name;
  }
  return buildCreateTable(draft, d).join("\n");
}
