import { useSyncExternalStore } from "react";

/**
 * Shared SQL text between the "SQL" console tab and the "Query" (visual builder) tab.
 *
 * Kept as a module-level store rather than page state so that:
 *  - the value survives a tab switch even though the views unmount, and
 *  - typing in one tab does not re-render the whole `Home` page tree.
 *
 * Mirrors the existing module-level `schemaCache` pattern in SqlConsole.tsx.
 */

let sharedSql = "";
const listeners = new Set<() => void>();

function emit() {
  for (const fn of listeners) fn();
}

export function getSharedSql(): string {
  return sharedSql;
}

export function setSharedSql(sql: string): void {
  if (sql === sharedSql) return;
  sharedSql = sql;
  emit();
}

export function subscribeSharedSql(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

/** Subscribe a component to the shared SQL text. */
export function useSharedSql(): string {
  return useSyncExternalStore(subscribeSharedSql, getSharedSql, getSharedSql);
}

/**
 * Determines whether a given SQL string is an unmodified/auto-generated template
 * (e.g., default `SELECT * FROM table LIMIT 50;` or `SELECT 1;` or empty),
 * so that we can know if switching tables should silently replace it or
 * prompt the user first before discarding custom query work.
 */
export function isAutoGeneratedSql(sql: string): boolean {
  if (!sql) return true;
  const trimmed = sql.trim();
  if (!trimmed) return true;
  if (/^SELECT\s+1\s*;?$/i.test(trimmed)) return true;

  // Matches auto SELECT * FROM <tableName> [LIMIT N];
  // Handles identifiers with quotes (", `, ', []) or dots (schema.table).
  const autoSelectRegex = /^SELECT\s+\*\s+FROM\s+(?:[`"'\[]?[\w\-.]+[`"'\]]?(?:\.[`"'\[]?[\w\-.]+[`"'\]]?)?)\s*(?:LIMIT\s+\d+)?\s*;?$/i;
  return autoSelectRegex.test(trimmed);
}

